'use client';

import React, { useEffect, useState } from 'react';
import GoBackButton from '@/components/GoBackButton';

interface MacdData {
  macd_line: number;
  signal_line: number;
  histogram: number;
}

interface BollingerBandsData {
  upper_band: number;
  middle_band: number;
  lower_band: number;
}

interface SignalData {
  coin_id: string;
  rsi: number;
  macd: MacdData;
  bollinger_bands: BollingerBandsData;
}

const SignalsPage = () => {
  const [signals, setSignals] = useState<SignalData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    const fetchSignals = async () => {
      setLoading(true);
      try {
        const response = await fetch('/signals/bitcoin');
        if (!response.ok) {
          throw new Error('Failed to fetch signals from backend');
        }
        const result: SignalData = await response.json();
        setSignals(result);
      } catch (err) {
        if (err instanceof Error) {
          setError(err.message);
        } else {
          setError('An unknown error occurred');
        }
      } finally {
        setLoading(false);
      }
    };

    fetchSignals();
  }, []);

  const getRsiInterpretation = (rsi: number) => {
    if (rsi > 70) return { text: "Overbought", className: "text-red-500" };
    if (rsi < 30) return { text: "Oversold", className: "text-green-500" };
    return { text: "Neutral", className: "text-yellow-500" };
  };

  const getMacdInterpretation = (macd: MacdData) => {
    if (macd.histogram > 0) return { text: "Bullish", className: "text-green-500" };
    if (macd.histogram < 0) return { text: "Bearish", className: "text-red-500" };
    return { text: "Neutral", className: "text-yellow-500" };
  };

  const rsiValue = signals?.rsi;
  const macdValue = signals?.macd;
  const bbValue = signals?.bollinger_bands;

  const rsiInterpretation = rsiValue ? getRsiInterpretation(rsiValue) : null;
  const macdInterpretation = macdValue ? getMacdInterpretation(macdValue) : null;

  return (
    <section id="signals" className="py-16">
      <div className="container mx-auto">
        <GoBackButton />
        <h2 className="font-heading text-4xl font-bold text-center mb-8">
          Buy/Sell Signal Panel
        </h2>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="bg-primary p-6 rounded-lg text-center">
            <h3 className="font-heading text-2xl font-bold mb-2">RSI (14)</h3>
            {loading ? (
              <p className="font-mono text-4xl mb-4">--</p>
            ) : error ? (
              <p className="font-mono text-2xl mb-4 text-red-500">Error</p>
            ) : (
              <p className="font-mono text-4xl mb-4">{rsiValue?.toFixed(2) ?? '--'}</p>
            )}
            <p className={`text-lg ${rsiInterpretation?.className ?? 'text-yellow-500'}`}>
              {loading ? 'Loading...' : error ? 'Failed' : rsiInterpretation?.text}
            </p>
          </div>
          <div className="bg-primary p-6 rounded-lg text-center">
            <h3 className="font-heading text-2xl font-bold mb-2">MACD</h3>
            {loading ? (
              <p className="font-mono text-2xl mb-4 text-gray-500">--</p>
            ) : error ? (
              <p className="font-mono text-2xl mb-4 text-red-500">Error</p>
            ) : (
                <p className={`font-mono text-2xl mb-4 ${macdInterpretation?.className ?? ''}`}>
                {macdInterpretation?.text}
              </p>
            )}
            <p className={`text-lg ${macdInterpretation?.className ?? 'text-yellow-500'}`}>
              {loading ? 'Loading...' : error ? 'Failed' : 'Signal based on histogram'}
            </p>
          </div>
          <div className="bg-primary p-6 rounded-lg text-center">
            <h3 className="font-heading text-2xl font-bold mb-2">Bollinger Bands</h3>
            {loading ? (
              <p className="font-mono text-lg mb-4">--</p>
            ) : error ? (
              <p className="font-mono text-lg mb-4 text-red-500">Error</p>
            ) : (
              <div className="font-mono text-sm">
                <p>Upper: {bbValue?.upper_band.toFixed(2)}</p>
                <p>Middle: {bbValue?.middle_band.toFixed(2)}</p>
                <p>Lower: {bbValue?.lower_band.toFixed(2)}</p>
              </div>
            )}
            <p className="text-lg text-yellow-500 mt-2">
              {loading ? 'Loading...' : error ? 'Failed' : 'Price within bands'}
            </p>
          </div>
        </div>
        <div className="mt-8 text-center bg-gray-800 border border-gray-700 text-gray-400 p-4 rounded-lg">
          <p className="font-bold">Signals are generated by our Python backend.</p>
        </div>
      </div>
    </section>
  );
};

export default SignalsPage;
